### PR TITLE
Closes #318 - Fixed jslint errors.

### LINKED ISSUE #318: Fix linting issues in existing JS files
To respect the rules defined in the `.jshintrc` added in #317.

### PR DESCRIPTION
**Pull request by AdrianGaudebert**
There are a few errors left. This one troubles me: 

```
./galaxy-api/api/models/game.js
  line 3  col 5  Redefinition of 'Promise'.
```

The line in question is:

```javascript
var Promise = require('es6-promise').Promise;
```

I don't understand what causes the problem, nor how to fix it. @cvan, any idea? 

The other question I have is a styling issue. In a case like this (in unit tests): 

```javascript
  lab.test('succeeds when server is connected with valid connection string', function (done) {
    expect('bla bla');
    // ...
  });
```

The first line is too long, how should I break it? I have 2 suggestions: 

```javascript
  lab.test(
    'succeeds when server is connected with valid connection string', 
    function (done) {
      expect('bla bla');
      // ...
    }
  );
```

or

```javascript
  lab.test(
  'succeeds when server is connected with valid connection string',
  function (done) {
    expect('bla bla');
    // ...
  });
```

What's best?

### CODE REVIEW

**Comment by cvan** [comment]
I would go with the first.

**Comment by cvan** [comment]
> I don't understand what causes the problem, nor how to fix it. @cvan, any idea?

`Promise` is defined in ES6, so we should call it `polyPromise` or something like that.

File: gulpfile.js [hunk 1]
```diff
@@ -1,8 +1,7 @@
-var exec = require('child_process').exec;
```
Comment (cvan) [inline gulpfile.js]: oh thanks

**Comment by cvan** [comment]
otherwise, looks great - thanks!

**Comment by AdrianGaudebert** [comment]
@cvan Should be good now, I addressed the Promise problem by replacing the import with
```javascript
require('es6-promise').polyfill();
```

(from the documentation here: https://www.npmjs.com/package/es6-promise )

File: api/models/game.js [hunk 2]
```diff
@@ -1,7 +1,9 @@
-var Promise = require('es6-promise').Promise;
+'use strict';
+
+// Polyfill for ES6's Promises, replaces the global namespace Promise object.
+require('es6-promise').polyfill();
```
Comment (cvan) [inline api/models/game.js]: can we do this somewhere globally like in `index.js` since everything imports that? or is there a safer way?

File: test/lib/db.js [hunk 3]
```diff
@@ -100,16 +101,18 @@ lab.experiment('db.disconnect', function () {
...
-    expect(function () {
+  lab.test(
+    'succeeds when server is connected with valid connection string',
+    function (done) {
+      expect(function () {
 
-      db.connect(settings.POSTGRES_URL);
-      db.disconnect();
-    }).to.not.throw();
+        db.connect(settings.POSTGRES_URL);
```
Comment (cvan) [inline test/lib/db.js]: ah, thanks

File: settings.js [hunk 4]
```diff
@@ -24,5 +24,7 @@ exports.POSTGRES_URL = 'postgres://localhost/galaxy-api';
 exports.SECRET = 'a secret string';
 
 for (var k in settings_local) {
-  exports[k] = settings_local[k];
+  if (settings_local.hasOwnProperty(k)) {
```
Comment (cvan) [inline settings.js]: you could just replace this `for` loop with

```js
Object.keys(settings_local).forEach(function (k) {
  exports[k] = settings_local[k];
});
```

File: api/routes.js [hunk 5]
```diff
@@ -129,13 +134,16 @@ module.exports = function (server) {
   Sample usage:
 
     curl -X PUT 'http://localhost:4000/games/1' \
-      -d '{"name": "mario bros", "game_url": "http://nintendo.com", "slug": "mario"}' \
+      -d '{"name": "mario bros", "game_url": "http://nintendo.com", ' \
```
Comment (cvan) [inline api/routes.js]: thanks. I know it can be a PITA at 79 characters per line.

**Comment by AdrianGaudebert** [comment]
@cvan comments addressed and branch rebased.

File: api/models/game.js (hunk 2 above)
Comment (cvan) [inline api/models/game.js]: @AdrianGaudebert ?

Comment (AdrianGaudebert) [inline api/models/game.js]: Oops! Fixed. :)

File: settings.js [hunk 6]
```diff
@@ -23,6 +23,6 @@ exports.POSTGRES_URL = 'postgres://localhost/galaxy-api';
 
 exports.SECRET = 'a secret string';
```
Comment (cvan) [inline settings.js]: I see a jshint error here:

```
/opt/galaxy-api/settings.js
  line 27  col 3  Missing "use strict" statement.
```

File: index.js [hunk 7]
```diff
@@ -1,6 +1,9 @@
 'use strict';
 var Hapi = require('hapi');
 
+// Polyfill for ES6's Promises, replaces the global namespace Promise object.
+require('es6-promise').polyfill();
```
Comment (cvan) [inline index.js]: so this works everywhere? even though I suggested this, I'm not sure this is the best spot. not sure though. it might be. I think it works.

Comment (cvan) [inline index.js]: tests and server still run fine, so I take it as a yes

Comment (AdrianGaudebert) [inline index.js]: Yeah testing locally without that line breaks the tests, I suppose that's a good proof. :)

File: settings.js (hunk 6 above)
Comment (AdrianGaudebert) [inline settings.js]: Damn that slipped through... Thanks for being cautious in your reviews!

Comment (AdrianGaudebert) [inline settings.js]: (And no cookies for me for not running ``gulp lint`` in a branch that aims at fixing lint errors... :( )

Comment (cvan) [inline settings.js]: heh np

**Comment by cvan** [comment]
```bash
[16:30:22] Using gulpfile /opt/galaxy-api/gulpfile.js
[16:30:22] Starting 'lint'...
[16:30:23] Finished 'lint' after 1.17 s
```

beautiful! :sun_with_face: :+1: 

# r+
